# Vandermonde Matrix

In [1]:
import numpy as np

## using Inbuilt numpy function np.vander(.....)

In [2]:
'''Using inbuilt vandermonde matrix function of numpy'''
print(__doc__)

x = np.array([3,1,6,7,4])
v_mat1 = np.vander(x, 4, increasing = True)
print('\n\nVandermonde Matrix with increasing = True:')
print(v_mat1)

v_mat2 = np.vander(x, 4)
print('\n\nVandermonde Matrix with increasing = False (default):')
print(v_mat2)

Using inbuilt vandermonde matrix function of numpy


Vandermonde Matrix with increasing = True:
[[  1   3   9  27]
 [  1   1   1   1]
 [  1   6  36 216]
 [  1   7  49 343]
 [  1   4  16  64]]


Vandermonde Matrix with increasing = False (default):
[[ 27   9   3   1]
 [  1   1   1   1]
 [216  36   6   1]
 [343  49   7   1]
 [ 64  16   4   1]]


# Defining a Vandermonde Matrix Generator.
## my_vandermonde_func(arr, n, increasing = False)

In [3]:
'''increase is False by default'''

def my_vandermonde_func(arr, n, increasing = False):
    mat = []
    for i in range(len(arr)):
        temp = []
        for j in range(n):
            if increasing == False:
                temp.append(arr[i]**(n-j-1))
            else:
                temp.append(arr[i]**j)
        mat.append(temp)
    mat = np.column_stack(mat).T
    return mat

# Usage

In [4]:
x = np.array([1,2,5,3,4])
print(my_vandermonde_func(x, 4))

[[  1   1   1   1]
 [  8   4   2   1]
 [125  25   5   1]
 [ 27   9   3   1]
 [ 64  16   4   1]]


In [5]:
print(my_vandermonde_func(x,4,increasing = True))

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   5  25 125]
 [  1   3   9  27]
 [  1   4  16  64]]


# Q.2 Moving Average Function

In [6]:
def moving_avg(arr, k):
    mov_avg = np.array([])
    for i in range(len(arr) - k + 1):
        s = 0
        for j in range(i, i+k):
            s = s + arr[j]/k
            s = round(s, 3)
        mov_avg = np.append(mov_avg, s)
    return mov_avg

# Example 1

In [7]:
x = [10, 20, 30, 40, 50, 60, 70, 80, 90 , 100]
k = 4
print([*moving_avg(x, k)])

[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]


# Test Array

In [8]:
x = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
# Window = 3
k = 3 
print([*moving_avg(x, k)])

[5.0, 4.667, 5.667, 6.667, 9.667, 28.667, 49.334, 72.667, 84.0, 93.333, 116.333]
